from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.database import get_db
from app.schema.mystery_flight_schema import MysteryFlightRequest, MysteryFlightResponse
from app.services.mystery_flight_service import book_mystery_flight

router = APIRouter(prefix="/gamified", tags=["Mystery Flight Roulette"])

@router.post("/mystery-booking", response_model=MysteryFlightResponse)
async def generate_mystery_trip(
    request: MysteryFlightRequest,
    db: Session = Depends(get_db)
):
    """
    Gamified Booking: The user specifies a budget and books a blind package.
    They receive a cryptic boarding pass and packing hints generated by AI, 
    but won't know the destination until the day of travel!
    """
    result = book_mystery_flight(request, db)
    
    if not result.get("success"):
        raise HTTPException(status_code=400, detail=result.get("error"))
        
    return result["data"]
