"""add razorpay_order_id

Revision ID: 3057961178cf
Revises: 4b8e98dbab12
Create Date: 2026-03-18 19:27:55.807067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3057961178cf'
down_revision: Union[str, Sequence[str], None] = '4b8e98dbab12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'razorpay_order_id')
    # ### end Alembic commands ###
