"""update trip_room_table

Revision ID: 31a75d00cc34
Revises: bd67cb27f0c6
Create Date: 2026-03-21 22:25:49.957494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a75d00cc34'
down_revision: Union[str, Sequence[str], None] = 'bd67cb27f0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_group_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('per_person', sa.Float(), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['trip_rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_trip_group_bookings_id'), 'trip_group_bookings', ['id'], unique=False)
    op.create_table('trip_member_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_booking_id'], ['trip_group_bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_booking_id', 'user_id', name='uq_group_payment_member')
    )
    op.create_index(op.f('ix_trip_member_payments_id'), 'trip_member_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_member_payments_id'), table_name='trip_member_payments')
    op.drop_table('trip_member_payments')
    op.drop_index(op.f('ix_trip_group_bookings_id'), table_name='trip_group_bookings')
    op.drop_table('trip_group_bookings')
    # ### end Alembic commands ###
