"""add_social_proof_package_model

Revision ID: 5fad18865901
Revises: 9ce5b84829d0
Create Date: 2026-03-19 23:03:06.985621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fad18865901'
down_revision: Union[str, Sequence[str], None] = '9ce5b84829d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_views_id'), 'package_views', ['id'], unique=False)
    op.create_index(op.f('ix_package_views_package_id'), 'package_views', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_views_viewed_at'), 'package_views', ['viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_views_viewed_at'), table_name='package_views')
    op.drop_index(op.f('ix_package_views_package_id'), table_name='package_views')
    op.drop_index(op.f('ix_package_views_id'), table_name='package_views')
    op.drop_table('package_views')
    # ### end Alembic commands ###
