"""add package_id to enquiry

Revision ID: 6ac89ccf3300
Revises: 138f021cb27d
Create Date: 2026-03-17 23:54:45.594135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac89ccf3300'
down_revision: Union[str, Sequence[str], None] = '138f021cb27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('package_id', sa.Integer(), nullable=True))
    op.alter_column('enquiries', 'agency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('enquiries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('enquiries', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'enquiries', 'travel_packages', ['package_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.alter_column('enquiries', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('enquiries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('enquiries', 'agency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('enquiries', 'package_id')
    # ### end Alembic commands ###
