"""add_trip_room_tables

Revision ID: 9ce5b84829d0
Revises: 3057961178cf
Create Date: 2026-03-19 19:51:06.921322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce5b84829d0'
down_revision: Union[str, Sequence[str], None] = '3057961178cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_rooms_id'), 'trip_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_trip_rooms_room_code'), 'trip_rooms', ['room_code'], unique=True)
    op.create_table('trip_room_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['trip_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_member')
    )
    op.create_index(op.f('ix_trip_room_members_id'), 'trip_room_members', ['id'], unique=False)
    op.create_table('trip_room_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['trip_rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'package_id', name='uq_room_package')
    )
    op.create_index(op.f('ix_trip_room_packages_id'), 'trip_room_packages', ['id'], unique=False)
    op.create_table('trip_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['trip_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_vote')
    )
    op.create_index(op.f('ix_trip_votes_id'), 'trip_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_votes_id'), table_name='trip_votes')
    op.drop_table('trip_votes')
    op.drop_index(op.f('ix_trip_room_packages_id'), table_name='trip_room_packages')
    op.drop_table('trip_room_packages')
    op.drop_index(op.f('ix_trip_room_members_id'), table_name='trip_room_members')
    op.drop_table('trip_room_members')
    op.drop_index(op.f('ix_trip_rooms_room_code'), table_name='trip_rooms')
    op.drop_index(op.f('ix_trip_rooms_id'), table_name='trip_rooms')
    op.drop_table('trip_rooms')
    # ### end Alembic commands ###
